import Head from 'next/head';

type CustomHeadProps = {
  title?: string;
};

const CustomHead: React.FC<CustomHeadProps> = ({ title = 'Task Manager' }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
export default CustomHead;
